# Generated by Django 5.1.8 on 2026-05-18 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smarko_App', '0002_logseguranca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(unique=True)),
                ('effective_date', models.DateTimeField()),
                ('privacy_policy_hash', models.CharField(help_text='SHA256 hash da política', max_length=64)),
                ('changes_summary', models.TextField()),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='DataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('retention_days', models.IntegerField(default=0, help_text='Dias de retenção (0 = indefinido)')),
            ],
            options={
                'verbose_name_plural': 'Data Categories',
            },
        ),
        migrations.RemoveField(
            model_name='logseguranca',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='bloqueado_ate',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='tentativas_falhas',
        ),
        migrations.AddField(
            model_name='logseguranca',
            name='usuario_nome',
            field=models.CharField(default='sistema', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('canceled', 'Cancelado'), ('completed', 'Completado')], default='pending', max_length=20)),
                ('confirmation_token', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['firebase_uid', 'status'], name='Smarko_App__firebas_a79efd_idx'), models.Index(fields=['confirmation_token'], name='Smarko_App__confirm_1c4d40_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('legal_basis', models.CharField(choices=[('consent', 'Consentimento'), ('contract', 'Contrato'), ('legal', 'Obrigação Legal'), ('vital', 'Proteção da Vida'), ('public', 'Interesse Público'), ('legitimate', 'Interesse Legítimo')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Se obrigatório para usar a app')),
                ('categories', models.ManyToManyField(related_name='purposes', to='Smarko_App.datacategory')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('version', models.IntegerField(default=1)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('accepted_privacy', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('purposes', models.ManyToManyField(related_name='consent_records', to='Smarko_App.datapurpose')),
            ],
            options={
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['firebase_uid', '-given_at'], name='Smarko_App__firebas_7c949b_idx'), models.Index(fields=['email', 'is_active'], name='Smarko_App__email_8e4dec_idx')],
            },
        ),
    ]
